"""DOR Web Dashboard - Visual Governance & Runtime Monitoring Interface."""

import os
import json
import sqlite3
import pandas as pd
import streamlit as st

st.set_page_config(
    page_title="DOR - Digital Organization Runtime",
    page_icon="⚡",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.title("⚡ Digital Organization Runtime (DOR) Dashboard")
st.markdown("Visual Governance, Active Workflows & Digital Actors Monitoring Interface")

# Database Connection
DB_PATH = os.getenv("DOR_DB_PATH", "dor_runtime.db")

def get_db_connection():
    if not os.path.exists(DB_PATH):
        st.warning(f"Database file `{DB_PATH}` not found. Run `python3 seed_data.py` first to initialize demo data.")
        return None
    return sqlite3.connect(DB_PATH)

conn = get_db_connection()

# Sidebar Navigation
st.sidebar.title("🏢 Navigation")
page = st.sidebar.radio(
    "Select View",
    ["Overview", "Active Workflows", "Governance Gates & Signatures", "Digital Actors", "Artifacts Registry"]
)

if page == "Overview":
    st.header("📊 Organization Metrics Overview")
    col1, col2, col3, col4 = st.columns(4)
    
    if conn:
        try:
            actors_count = pd.read_sql_query("SELECT COUNT(*) as count FROM actors", conn)['count'][0]
            workflows_count = pd.read_sql_query("SELECT COUNT(*) as count FROM workflow_templates", conn)['count'][0]
            artifacts_count = pd.read_sql_query("SELECT COUNT(*) as count FROM artifacts", conn)['count'][0]
            orgs_count = pd.read_sql_query("SELECT COUNT(*) as count FROM organizations", conn)['count'][0]
        except Exception:
            actors_count, workflows_count, artifacts_count, orgs_count = 2, 1, 1, 1

        col1.metric("Organizations", orgs_count)
        col2.metric("Digital & Human Actors", actors_count)
        col3.metric("Workflow Templates", workflows_count)
        col4.metric("Artifacts Generated", artifacts_count)
    else:
        col1.metric("Organizations", "1")
        col2.metric("Digital & Human Actors", "2")
        col3.metric("Workflow Templates", "1")
        col4.metric("Artifacts Generated", "1")

    st.subheader("🏛️ Digital Organization Architecture")
    st.info("DOR runs autonomous agents (Actors) executing Intents through strict Governance Workflows.")

elif page == "Active Workflows":
    st.header("🔄 Active Workflows & State Transitions")
    st.markdown("Monitor real-time workflow state transitions across departments.")
    
    # Mock / DB Workflows Table
    workflows_data = [
        {"ID": "wf-101", "Name": "Feature Development: OAuth2 Auth", "State": "REVIEW", "Gate Pending": "Security Review", "Actor": "EIRA AI Developer"},
        {"ID": "wf-102", "Name": "Architecture Review: Payment Gateway", "State": "DESIGN", "Gate Pending": "None", "Actor": "Claude-5 Senior Architect"},
        {"ID": "wf-103", "Name": "Infrastructure Setup: Terraform K8s", "State": "IMPLEMENTATION", "Gate Pending": "DevOps Supervisor", "Actor": "GitHub Service Bot"},
    ]
    st.dataframe(pd.DataFrame(workflows_data), use_container_width=True)

elif page == "Governance Gates & Signatures":
    st.header("🛡️ Governance Gates & Approval Action Center")
    st.markdown("Human-in-the-loop review interface for signing artifacts and approving state transitions.")
    
    st.subheader("Pending Gate Approvals")
    
    with st.form("gate_approval_form"):
        st.write("### Review Gate: Security & Architecture Audit")
        st.text("Artifact: auth_service.py (SHA-256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855)")
        st.text("Generated by: EIRA AI Developer")
        
        status_choice = st.selectbox("Decision", ["APPROVED", "REJECTED", "NEEDS_CHANGES"])
        comments = st.text_area("Audit Comments", "Code verified against security guidelines. Clean implementation.")
        
        submitted = st.form_submit_button("Submit Governance Decision")
        if submitted:
            st.success(f"Decision '{status_choice}' successfully recorded for Artifact auth_service.py!")

elif page == "Digital Actors":
    st.header("🤖 Digital & Human Actors Registry")
    actors_data = [
        {"ID": "actor-1", "Identity": "EIRA AI Developer", "Type": "DIGITAL_EMPLOYEE", "Status": "ACTIVE", "Role": "Senior AI Engineer"},
        {"ID": "actor-2", "Identity": "Human Supervisor", "Type": "HUMAN", "Status": "ACTIVE", "Role": "Code Reviewer"},
        {"ID": "actor-3", "Identity": "GitHub Service Bot", "Type": "SERVICE", "Status": "ACTIVE", "Role": "CI/CD Executor"},
    ]
    st.table(pd.DataFrame(actors_data))

elif page == "Artifacts Registry":
    st.header("📦 Artifacts & Cryptographic Audit Trail")
    artifacts_data = [
        {"ID": "art-001", "Name": "auth_service.py", "Type": "IMPLEMENTATION", "Hash (SHA-256)": "a7c82...99f1", "State": "APPROVED"},
        {"ID": "art-002", "Name": "architecture_adr.md", "Type": "SPECIFICATION", "Hash (SHA-256)": "f12a3...88d2", "State": "RELEASED"},
    ]
    st.dataframe(pd.DataFrame(artifacts_data), use_container_width=True)
