"""Unit tests for Quality-First Hybrid Router."""

import pytest

from phase4.adaptation.quality_router import (
    ModelEndpoint,
    ModelTier,
    NoAvailableProviderError,
    Provider,
    QualityFirstRouter,
    RoutingRequest,
    TaskSensitivity,
)
from phase4.authority.adapter import RiskLevel


def test_routine_task_routes_to_tier_1_free():
    """Test that routine tasks like doc ingestion or boilerplate route to Tier 1 local/free model."""
    router = QualityFirstRouter()
    req = RoutingRequest(
        task_id="task-doc-1",
        sensitivity=TaskSensitivity.ROUTINE,
        risk_level=RiskLevel.LOW,
        description="Ingest markdown documentation into knowledge graph",
        is_code_generation=False,
    )

    decision = router.route(req)

    assert decision.selected_tier == ModelTier.TIER_1_LOCAL_FREE
    assert decision.selected_provider in (Provider.ROOL_CORE, Provider.LIBRECHAT_PROXY)
    assert decision.fallback_used is False
    assert decision.requires_council_verification is False


def test_high_stakes_task_routes_to_tier_3_and_requires_council():
    """Test that high-stakes tasks route to Tier 3 premium models and require Council verification."""
    router = QualityFirstRouter()
    req = RoutingRequest(
        task_id="task-council-delib-1",
        sensitivity=TaskSensitivity.HIGH_STAKES,
        risk_level=RiskLevel.HIGH,
        description="Deliberate on critical authentication refactoring",
        is_code_generation=False,
    )

    decision = router.route(req)

    assert decision.selected_tier == ModelTier.TIER_3_PREMIUM_FRONTIER
    assert decision.selected_provider in (Provider.ANTHROPIC, Provider.OPENAI)
    assert decision.requires_council_verification is True


def test_quality_assurance_gate_enforces_council_for_cheaper_code_generation():
    """Test QA Gate: Code generated by cheaper/free models MUST require Council verification."""
    router = QualityFirstRouter()

    # Routine code generation on Tier 1
    req_routine_code = RoutingRequest(
        task_id="task-code-gen-1",
        sensitivity=TaskSensitivity.ROUTINE,
        risk_level=RiskLevel.LOW,
        description="Generate boilerplate pydantic model schema",
        is_code_generation=True,
    )
    dec_routine = router.route(req_routine_code)
    assert dec_routine.selected_tier == ModelTier.TIER_1_LOCAL_FREE
    assert dec_routine.requires_council_verification is True

    # Standard code generation on Tier 2
    req_standard_code = RoutingRequest(
        task_id="task-code-gen-2",
        sensitivity=TaskSensitivity.STANDARD,
        risk_level=RiskLevel.MEDIUM,
        description="Implement database retry logic with backoff",
        is_code_generation=True,
    )
    dec_standard = router.route(req_standard_code)
    assert dec_standard.selected_tier == ModelTier.TIER_2_STANDARD
    assert dec_standard.requires_council_verification is True


def test_fallback_selection_when_tier_unavailable():
    """Test that router gracefully falls back when target tier providers are down."""
    endpoints = [
        # Tier 1 endpoints unavailable
        ModelEndpoint(Provider.ROOL_CORE, "rool-core-local", ModelTier.TIER_1_LOCAL_FREE, 0.0, is_available=False),
        ModelEndpoint(Provider.LIBRECHAT_PROXY, "librechat-selfhosted", ModelTier.TIER_1_LOCAL_FREE, 0.0, is_available=False),
        # Tier 2 available
        ModelEndpoint(Provider.OPENAI, "gpt-4o-mini", ModelTier.TIER_2_STANDARD, 0.15, is_available=True),
    ]
    router = QualityFirstRouter(endpoints=endpoints)

    req = RoutingRequest(
        task_id="task-fallback-1",
        sensitivity=TaskSensitivity.ROUTINE,
        risk_level=RiskLevel.LOW,
        description="Routine task fallback test",
        is_code_generation=False,
    )

    decision = router.route(req)

    assert decision.selected_tier == ModelTier.TIER_2_STANDARD
    assert decision.selected_provider == Provider.OPENAI
    assert decision.fallback_used is True


def test_no_available_provider_raises_error():
    """Test that NoAvailableProviderError is raised if no endpoints in fallback chain are available."""
    endpoints = [
        ModelEndpoint(Provider.ANTHROPIC, "claude-3-5-sonnet", ModelTier.TIER_3_PREMIUM_FRONTIER, 3.0, is_available=False),
    ]
    router = QualityFirstRouter(endpoints=endpoints)

    req = RoutingRequest(
        task_id="task-fail-1",
        sensitivity=TaskSensitivity.HIGH_STAKES,
        risk_level=RiskLevel.CRITICAL,
        description="Critical security review with no available models",
    )

    with pytest.raises(NoAvailableProviderError):
        router.route(req)
