"""Phase 4 Council Deliberation and Dispute Protocol.

Orchestrates multi-agent deliberation cycles, evidence-backed disputes,
and consensus threshold evaluations.
"""

from phase4.verification.allocation_selector import (
    CouncilRunSelection,
    CouncilSelectionError,
    DeterministicCouncilSelector,
    FrozenCouncilAssignment,
    SelectionCandidate,
    SelectionReceipt,
    SelectionRequestContext,
)

from .configuration import (
    AllocationMember,
    AutonomyLevel,
    CouncilRoleDefinition,
    CouncilTemplate,
    IndependenceLevel,
    ProtocolFunction,
    RoleAllocationPool,
    TemplateStage,
)
from .dispute import DisputeProtocol, DisputeProtocolError
from .execution_events import (
    CouncilEventBindingError,
    CouncilFailureEventHandler,
    execution_failure_event_from_result,
)
from .models import Dispute, DisputeStatus, SessionState, Vote
from .orchestrator import (
    CouncilOrchestrationError,
    CouncilOrchestrator,
    CouncilOrchestratorResult,
    CouncilProvider,
    CouncilProviderError,
    CouncilProviderResponseError,
    CouncilRiskEvaluator,
    CouncilStartError,
    DefaultCouncilRiskEvaluator,
    DeliberationConfig,
)
from .roles import (
    ROLE_PERSONAS,
    CouncilAgenda,
    CouncilDisputeProposal,
    CouncilDisputeResolution,
    CouncilOrchestrationOutcome,
    CouncilRole,
    CouncilRoleAssignment,
    CouncilTurnDecision,
    CouncilTurnKind,
    CouncilTurnRequest,
    CouncilTurnResponse,
    CouncilTurnRouteBinding,
    RolePersona,
)
from .routing import (
    AssignmentRoute,
    CatalogRouteSnapshot,
    CouncilAssignmentPlan,
    CouncilProviderFactory,
    CouncilProviderRouter,
    ProviderRoutingError,
    RouteCatalogResolver,
    TemplateCouncilProviderRouter,
)
from .runtime_models import (
    CouncilOutboxEvent,
    CouncilRuntimeEventType,
    CouncilSessionBinding,
    ExecutionFailedEvent,
    PersistedDeliberation,
)
from .session import DeliberationError, DeliberationSession
from .store import (
    CouncilConflictError,
    CouncilNotFoundError,
    CouncilStore,
    CouncilStoreError,
)

__all__ = [
    "AllocationMember",
    "AssignmentRoute",
    "AutonomyLevel",
    "ROLE_PERSONAS",
    "CouncilAgenda",
    "CouncilAssignmentPlan",
    "CouncilConflictError",
    "CouncilDisputeProposal",
    "CouncilDisputeResolution",
    "CouncilEventBindingError",
    "CouncilFailureEventHandler",
    "CouncilNotFoundError",
    "CouncilOrchestrationError",
    "CouncilOrchestrationOutcome",
    "CouncilOrchestrator",
    "CouncilOrchestratorResult",
    "CouncilOutboxEvent",
    "CouncilProvider",
    "CouncilProviderFactory",
    "CouncilProviderRouter",
    "CouncilProviderError",
    "CouncilProviderResponseError",
    "CouncilRiskEvaluator",
    "CouncilRoleDefinition",
    "CouncilRole",
    "CouncilRoleAssignment",
    "CouncilRuntimeEventType",
    "CouncilRunSelection",
    "CouncilSelectionError",
    "CouncilSessionBinding",
    "CouncilStartError",
    "CouncilStore",
    "CouncilStoreError",
    "CouncilTurnDecision",
    "CouncilTurnKind",
    "CouncilTurnRequest",
    "CouncilTurnRouteBinding",
    "CouncilTurnResponse",
    "CouncilTemplate",
    "DefaultCouncilRiskEvaluator",
    "DeterministicCouncilSelector",
    "DeliberationConfig",
    "DeliberationError",
    "DeliberationSession",
    "Dispute",
    "DisputeProtocol",
    "DisputeProtocolError",
    "DisputeStatus",
    "ExecutionFailedEvent",
    "FrozenCouncilAssignment",
    "CatalogRouteSnapshot",
    "IndependenceLevel",
    "PersistedDeliberation",
    "ProtocolFunction",
    "ProviderRoutingError",
    "RoleAllocationPool",
    "RolePersona",
    "RouteCatalogResolver",
    "SessionState",
    "SelectionCandidate",
    "SelectionRequestContext",
    "SelectionReceipt",
    "TemplateStage",
    "TemplateCouncilProviderRouter",
    "Vote",
    "execution_failure_event_from_result",
]
