"""Quality-First Hybrid Router balancing cost-effective routing and strict verification."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import uuid4

from .models import RiskLevel


class ModelTier(str, Enum):
    TIER_1_LOCAL_FREE = "TIER_1_LOCAL_FREE"       # Local Rool core, LibreChat self-hosted proxy
    TIER_2_STANDARD = "TIER_2_STANDARD"           # Cost-efficient cloud models (DeepSeek, GPT-4o-mini)
    TIER_3_PREMIUM_FRONTIER = "TIER_3_PREMIUM"    # Top-tier validation models (Claude 3.5 Sonnet, GPT-4o, o1)


class Provider(str, Enum):
    ROOL_CORE = "rool_core"
    LIBRECHAT_PROXY = "librechat_proxy"
    OPENAI = "openai"
    ANTHROPIC = "anthropic"
    DEEPSEEK = "deepseek"


class TaskSensitivity(str, Enum):
    ROUTINE = "ROUTINE"                          # Boilerplate, doc ingestion, linting, simple formatting
    STANDARD = "STANDARD"                        # Normal feature implementation, unit test generation
    HIGH_STAKES = "HIGH_STAKES"                  # Council deliberation, security reviews, critical refactoring


@dataclass(frozen=True)
class ModelEndpoint:
    provider: Provider
    model_name: str
    tier: ModelTier
    cost_per_million_tokens: float
    is_available: bool = True


@dataclass(frozen=True)
class RoutingRequest:
    task_id: str
    sensitivity: TaskSensitivity
    risk_level: RiskLevel
    description: str
    is_code_generation: bool = False
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class RoutingDecision:
    decision_id: str
    task_id: str
    sensitivity: TaskSensitivity
    risk_level: RiskLevel
    selected_provider: Provider
    selected_model: str
    selected_tier: ModelTier
    requires_council_verification: bool
    rationale: str
    fallback_used: bool = False
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class RouterConfigurationError(Exception):
    """Raised when the router configuration is invalid."""


class NoAvailableProviderError(Exception):
    """Raised when no healthy provider is available for the required tier."""


class QualityFirstRouter:
    """Dynamic hybrid router enforcing cost optimization and quality/safety gates."""

    DEFAULT_ENDPOINTS = [
        # Tier 1 (Free / Local / Self-hosted)
        ModelEndpoint(Provider.ROOL_CORE, "rool-core-local", ModelTier.TIER_1_LOCAL_FREE, 0.0),
        ModelEndpoint(Provider.LIBRECHAT_PROXY, "librechat-selfhosted", ModelTier.TIER_1_LOCAL_FREE, 0.0),

        # Tier 2 (Standard / Cost-efficient)
        ModelEndpoint(Provider.DEEPSEEK, "deepseek-coder-v2", ModelTier.TIER_2_STANDARD, 0.28),
        ModelEndpoint(Provider.OPENAI, "gpt-4o-mini", ModelTier.TIER_2_STANDARD, 0.15),

        # Tier 3 (Premium Frontier / High-stakes validation)
        ModelEndpoint(Provider.ANTHROPIC, "claude-3-5-sonnet", ModelTier.TIER_3_PREMIUM_FRONTIER, 3.00),
        ModelEndpoint(Provider.OPENAI, "gpt-4o", ModelTier.TIER_3_PREMIUM_FRONTIER, 2.50),
    ]

    def __init__(self, endpoints: Optional[List[ModelEndpoint]] = None) -> None:
        self.endpoints: List[ModelEndpoint] = endpoints if endpoints is not None else list(self.DEFAULT_ENDPOINTS)

    def route(self, request: RoutingRequest) -> RoutingDecision:
        """Route task request to optimal model tier with mandatory Council gating."""
        target_tier = self._determine_target_tier(request)
        endpoint, fallback_used = self._select_endpoint_with_fallback(target_tier)

        # Quality Assurance Gate:
        # 1. Any HIGH_STAKES task requires Council verification.
        # 2. ANY code generated by a cheaper/free tier (Tier 1 or Tier 2) MUST undergo mandatory Council verification.
        # 3. Any task with HIGH or CRITICAL risk requires Council verification.
        requires_verification = (
            request.sensitivity == TaskSensitivity.HIGH_STAKES
            or request.risk_level in (RiskLevel.HIGH, RiskLevel.CRITICAL)
            or (request.is_code_generation and endpoint.tier in (ModelTier.TIER_1_LOCAL_FREE, ModelTier.TIER_2_STANDARD))
        )

        rationale = (
            f"Routed to {endpoint.provider.value}:{endpoint.model_name} ({endpoint.tier.value}). "
            f"Sensitivity={request.sensitivity.value}, Risk={request.risk_level.value}. "
            f"Council verification required={requires_verification}."
        )
        if fallback_used:
            rationale += " (Fallback provider selected due to primary tier unavailability)."

        return RoutingDecision(
            decision_id=str(uuid4()),
            task_id=request.task_id,
            sensitivity=request.sensitivity,
            risk_level=request.risk_level,
            selected_provider=endpoint.provider,
            selected_model=endpoint.model_name,
            selected_tier=endpoint.tier,
            requires_council_verification=requires_verification,
            rationale=rationale,
            fallback_used=fallback_used,
        )

    def _determine_target_tier(self, request: RoutingRequest) -> ModelTier:
        """Evaluate sensitivity and risk to determine the minimum safe model tier."""
        if request.sensitivity == TaskSensitivity.HIGH_STAKES or request.risk_level in (RiskLevel.HIGH, RiskLevel.CRITICAL):
            return ModelTier.TIER_3_PREMIUM_FRONTIER

        if request.sensitivity == TaskSensitivity.STANDARD or request.risk_level == RiskLevel.MEDIUM:
            return ModelTier.TIER_2_STANDARD

        # Routine tasks (boilerplate, raw doc ingestion, linting) -> Tier 1
        return ModelTier.TIER_1_LOCAL_FREE

    def _select_endpoint_with_fallback(self, target_tier: ModelTier) -> tuple[ModelEndpoint, bool]:
        """Select healthy endpoint for tier, falling back upward or downward gracefully."""
        # Preference sequence depending on target tier
        tier_preferences = {
            ModelTier.TIER_3_PREMIUM_FRONTIER: [
                ModelTier.TIER_3_PREMIUM_FRONTIER,
            ],
            ModelTier.TIER_2_STANDARD: [
                ModelTier.TIER_2_STANDARD,
                ModelTier.TIER_3_PREMIUM_FRONTIER,
                ModelTier.TIER_1_LOCAL_FREE,
            ],
            ModelTier.TIER_1_LOCAL_FREE: [
                ModelTier.TIER_1_LOCAL_FREE,
                ModelTier.TIER_2_STANDARD,
                ModelTier.TIER_3_PREMIUM_FRONTIER,
            ],
        }

        search_tiers = tier_preferences.get(target_tier, [target_tier])

        for tier in search_tiers:
            available = [e for e in self.endpoints if e.tier == tier and e.is_available]
            if available:
                # Pick lowest cost within tier
                available.sort(key=lambda ep: ep.cost_per_million_tokens)
                return available[0], (tier != target_tier)

        raise NoAvailableProviderError(f"No available endpoints for requested tier {target_tier.value} or fallback tiers.")
